### PR TITLE
Assignment 1

### PR DESCRIPTION
**Pull request by Disciple4GIT**
Pull Request for Assignment 1.

### CODE REVIEW

**Comment by mmwoodfo** [comment]
@Disciple4GIT Do not leave multiple assignments open or I will grade the first one I come across. I am going to give you a grade for the other assignment you have, just because this is the first assignment. But in the future, this PR would be the assignment you get graded on. Be sure to close your PR if you don't want it graded.

**Comment by Disciple4GIT** [comment]
I collaborated with Nate Nelson for this assignment. I thought I closed all those other ones I opened.

**Comment by mmwoodfo** [comment]
@Disciple4GIT That is no problem, just make sure you avoid that in the future. I don't think I have a name mapping for you, have you filled out the form to map your github name to your real name? 
https://forms.office.com/pages/responsepage.aspx?id=BxkyN6UUkEOYfewMZsZVzXsAdSGbOdZIkTYGnAkObtZUMUROU1BPTjdaSzcxVUtCMTlTTk9OVlJQOC4u

**Comment by Disciple4GIT** [comment]
My name is Michael Moses Wright, and i did fill out the form I believe

**Comment by mmwoodfo** [comment]
@Disciple4GIT Thank you, I will update your grade. I don't see you on the sheet, but I may have an outdated version. I'll request the latest version from Mark and if you're still not on there I'll just fill it out for you, so no worries.

**Pull request closed without merging**
