### PR TITLE
Assignment5+6 @ Disciple4GIT

### PR DESCRIPTION
**Pull request by nwnel-017**

### CODE REVIEW

**Comment by mmwoodfo** [comment]
This is late - the assignment was due on the 21st.

**Comment by nwnel-017** [comment]
I thought our final version due Thursday as usual? I submitted our assignment on the 21st, and made a few edits after getting our code reviewed, this is our final version

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mmwoodfo** [comment]
Yes, but the PR is due on Monday. It looks like this PR was submitted on Thursday?

**Comment by mmwoodfo** [comment]
@Disciple4GIT Did you do a PR review? I can't seem to find one for you.

**Comment by Disciple4GIT** [comment]
> @Disciple4GIT Did you do a PR review? I can't seem to find one for you.

If I’m gonna be honest…..I completely forgot to do that. So no I didn’t do one, my apologies

**Pull request closed without merging**
