### PR TITLE
Assignment1

### PR DESCRIPTION
**Pull request by whitneybolar**

### CODE REVIEW

**Comment by whitneybolar** [comment]
Peer Review Partner: Kelsey McMahon

**Comment by mmwoodfo** [comment]
@whitneybolar Please put your partner in the description of the PR and note them as your partner, not your reviewer.

**Comment by whitneybolar** [comment]
Hello Meghan,

I am confused. Kelsey did peer review my work because she already had a partner. Am I supposed to make my peer reviewer my partner? Am I only supposed to have a peer review partner if they do not have a partner? If I am doing my assignments on my own, will we get a peer review partner automatically or do I need to search for one?

-Whitney Bolar

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mmwoodfo** [comment]
@whitneybolar I see that, it looks like she worked on this PR: https://github.com/IntelliTect-Samples/EWU-CSCD371-2022-Winter/pull/44

Where is her review though? I don't see if on this PR. I also don't see a review done by you?

**Comment by whitneybolar** [comment]
Meghan,

She only reviewed my work because she already had a partner. For the review, was it supposed to be a list of things that they recommend, or did I have to make changes to my code? Overall, I did not have to make changes. She brought up different ways I could have the same outcome, but everything checked out.

-Whitney Bolar

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mmwoodfo** [comment]
@whitneybolar so the issue isn't if Kelsey did a review or not, the issue is that you don't have a code review. Here is an example of a pull request with a code review done for it:
https://github.com/IntelliTect-Samples/EWU-CSCD371-2022-Winter/pull/34

You can see, ericlplanteschool is the owner of the PR, and dcox2005 reviewed it. So in this case, ericlplanteschool doesn't get any additional points for the PR, but dcox2005 does as he is the one that did the review. For ericplanteschool to receive points, he'd have to go review someone elses PR.

So the problem is that I can't find your PR review. Sometimes I just miss them when grading, so if you have reviewed someone's PR would you be able to provide me with the name of the student you reviewed and/or the PR # your review is on?

**Comment by whitneybolar** [comment]
Okay, I understand. I thought the priority was to get someone to peer review your work and not the other way around. I thought since my peer review "partner" already had a partner, I did not need to do a peer review. I asked my peer reviewer if they would like me to review their work and she said she was good because she already had an official partner. I saw that you closed all the pull requests. Is there a way for me to make up for the points? I do not want to worry about my grade when I should be learning. I can give you a doctors note explaining why I have a hard time following directions. I am currently in the process of filling out paper work with EWU disability services to make this an official accommodation.

-Whitney Bolar
________________________________

**Comment by mmwoodfo** [comment]
@whitneybolar let me talk with Mark and Grant. We will get back to you.

**Comment by whitneybolar** [comment]
I forgot to tell you, but I was also not able to access the recordings because my macOS was temporarily disabled and my windows OS would make the videos glitch and freeze. My macOS is back and running since yesterday. I will try accessing the lectures soon.


Best regards,


Whitney Bolar ​

EWU | Technical Communication and Computer Science Major

[mobile] 425.518.4658
***@***.***


pronouns: they/them/their


________________________________

**Comment by mmwoodfo** [comment]
@whitneybolar Okay, Mark has suggested that to make up for the lost points, you perform two PR reviews for Assignment 2. So do a PR review for two separate pull requests. If you have any questions, please feel free to ask them on Tuesday either before or after class, or during the break.

**Comment by whitneybolar** [comment]
That makes sense, thank you for understanding.

-Whitney Bolar

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
