### PR TITLE
Assignment1

### PR DESCRIPTION
**Pull request by ericlplanteschool**
solutions for issues 1 & 2 provided

### CODE REVIEW

**Comment by dcox2005** [comment]
Correct changes implemented for base assignment.  One short note, instead of  changing GetPercentCorrect into 3 lines of code, simply change:
return (numberCorrectAnswers / numberOfQuestions * 100) + "%"; 
to
return ((float) numberCorrectAnswers / numberOfQuestions * 100) + "%"; 

A simple cast of float to one of the numbers would make the whole output a float.

Assignment
Pull Request title includes "Assignment 1" in the title ✔
Pull Request targets Assignment 1 branch ✔
Issue 1: Application no longer crashes ✔
Issue 2: Unit test properly passes ✔
Extra Credit
Issue 3: Feature request implemented ❌
Issue 3: Feature request unit tested ❌

**Review by mmwoodfo — COMMENTED** [review]
👍🏻

**Comment by mmwoodfo** [comment]
The PR review by @dcox2005 has a good suggestion in it for future projects.

**Comment by mmwoodfo** [comment]
@ericlplanteschool  did you do a PR review? If so, can you provide me with the name of the student you did the review for and/or the PR #?

Thank you.

**Comment by ericlplanteschool** [comment]
> @ericlplanteschool did you do a PR review? If so, can you provide me with the name of the student you did the review for and/or the PR #?
> 
> Thank you.

@jmeadowcroft

**Comment by ericlplanteschool** [comment]
@mmwoodfo I completed a review for @jmeadowcroft

**Comment by mmwoodfo** [comment]
@ericlplanteschool great, thank you! I will update your grade.

**Pull request closed without merging**
